---
title: Data Visualization
format:
  html: default
  pdf: default
---

```{r}
library(tidyverse)
library(gapminder)
data(gapminder)
head(gapminder)
```

```{r}
summary(gapminder)
```

```{r}
gapminder_2007 <- gapminder |>
  filter(year == 2007)

ggplot(data = gapminder_2007,
       mapping = aes(x = gdpPercap,
                     y = lifeExp,
                     color = continent,
                     size = pop)) +
  geom_point() +
  scale_x_log10() +
  scale_color_viridis_d()
```

```{r}
gapminder_1957 <- gapminder |>
  filter(year == 1957)

ggplot(data = gapminder_1957,
       mapping = aes(x = gdpPercap,
                     y = lifeExp,
                     color = continent,
                     size = pop)) +
  geom_point() +
  scale_x_log10() +
  scale_color_viridis_d()
```

```{r}
gapminder_1982 <- gapminder |>
  filter(year == 1982)

ggplot(data = gapminder_1957,
       mapping = aes(x = gdpPercap,
                     y = lifeExp,
                     color = continent,
                     size = pop)) +
  geom_point() +
  scale_x_log10() +
  scale_color_viridis_d()
```

```{r}
gapminder_subset <- gapminder |>
  filter(year == 1957 | year == 1982 | year == 2007)

ggplot(data = gapminder_subset,
       mapping = aes(x = gdpPercap,
                     y = lifeExp,
                     color = continent,
                     size = pop)) +
  geom_point() +
  scale_x_log10()+
  facet_grid(~year)
```

